// Conteúdo das páginas de processo e setor (SEO). Apenas informações já presentes no site/material da TFM.
export const processos = [
  { slug: 'hvof', faq: [{"q": "HVOF substitui o cromo duro?", "a": "Em muitas aplicações com abrasão severa, sim. O carbeto de tungstênio aplicado por HVOF costuma ter maior resistência ao desgaste; a escolha final depende do diagnóstico da peça."}, {"q": "A peça esquenta ou empena no HVOF?", "a": "Não de forma significativa: no HVOF a peça se mantém abaixo de cerca de 150 °C durante a aplicação, sem empenar nem alterar o material de base."}], nome: 'HVOF', titulo: 'Revestimento HVOF (aspersão térmica hipersônica)',
    resumo: 'Camadas muito densas e aderentes de carbeto de tungstênio e ligas especiais, aplicadas em velocidade supersônica para resistir a abrasão, erosão e corrosão.',
    como: 'No HVOF (High Velocity Oxy-Fuel), a combustão em alta pressão acelera as partículas de pó a velocidades supersônicas. Elas atingem a peça com grande energia e formam um revestimento de baixa porosidade e alta aderência, com o substrato mantido em baixa temperatura.',
    beneficios: ['Alta dureza e resistência à abrasão', 'Baixa porosidade e alta aderência', 'Alternativa ao cromo duro em abrasão severa', 'Substrato em baixa temperatura, sem distorção'],
    materiais: ['Carbeto de tungstênio (WC-Co)', 'WC-CrC-Ni', 'Carbeto de cromo', 'Ligas de níquel'],
    aplicacoes: ['Pistões e hastes hidráulicas', 'Bobinas de trefila', 'Eixos de bombas e compressores', 'Roscas transportadoras', 'Válvulas e sedes'],
    caso: 'Pistão de prensa hidráulica (papel e celulose): substituição do cromo duro por carbeto de tungstênio aplicado por HVOF, aumentando a vida útil da camada.' },
  { slug: 'arc-spray', faq: [{"q": "Arc Spray serve para recuperar medida?", "a": "Sim. A alta taxa de deposição torna o Arc Spray econômico para recuperação dimensional, seguida de usinagem de acabamento."}, {"q": "Pode ser feito em campo?", "a": "Sim, o Arc Spray é aplicável em campo em muitos casos, como estruturas e grandes superfícies."}], nome: 'Arc Spray', titulo: 'Metalização por Arc Spray',
    resumo: 'Alta taxa de deposição para recuperação dimensional e proteção de grandes áreas contra corrosão.',
    como: 'Dois arames metálicos são fundidos por um arco elétrico e atomizados por ar comprimido, projetando gotas sobre a superfície preparada. É ideal para grandes áreas e recuperação de cotas com produtividade.',
    beneficios: ['Alta produtividade em grandes áreas', 'Recuperação dimensional econômica', 'Proteção anticorrosiva (zinco, alumínio)', 'Aplicável em campo'],
    materiais: ['Aço inox (ex.: INOX 420)', 'Aço carbono', 'Zinco e alumínio', 'Bronze e metal patente'],
    aplicacoes: ['Camisas e colos de eixos', 'Bobinas e polias', 'Estruturas navais e offshore', 'Mancais'],
    caso: 'Camisa recuperada no colo externo pelo processo Arc Spray com aço inox martensítico, seguida de usinagem de acabamento.' },
  { slug: 'pta', faq: [{"q": "PTA é soldagem ou aspersão?", "a": "É um processo de soldagem por plasma: o revestimento é fundido sobre a peça e forma ligação metalúrgica, diferente da aspersão térmica."}, {"q": "Quando escolher PTA?", "a": "Quando a peça sofre impacto e abrasão severa ou precisa de camada espessa com ligação metalúrgica, como sedes de válvulas e componentes de mineração."}], nome: 'PTA', titulo: 'Revestimento por PTA (plasma de arco transferido)',
    resumo: 'Camada soldada com ligação metalúrgica e baixa diluição, para impacto, abrasão e altas temperaturas.',
    como: 'No PTA, o arco de plasma é transferido para a peça e funde o pó metálico diretamente sobre a superfície, formando um cordão soldado de alta resistência e baixa diluição com o metal base.',
    beneficios: ['Ligação metalúrgica com a peça', 'Baixa diluição e controle preciso', 'Resistência a impacto e abrasão severa', 'Camadas espessas'],
    materiais: ['Ligas de cobalto (Stellite)', 'Ligas de níquel', 'Ligas de níquel com carbonetos'],
    aplicacoes: ['Sedes de válvulas', 'Componentes de mineração', 'Ferramentas e facas industriais', 'Peças sujeitas a impacto'] },
  { slug: 'laser-cladding', faq: [{"q": "O que é laser cladding?", "a": "É a deposição de uma liga metálica fundida por feixe laser sobre a peça. O resultado é uma camada soldada, com ligação metalúrgica, diluição mínima e pouca entrada de calor."}, {"q": "O laser pode ser feito na minha planta?", "a": "Sim. Nosso laser é conduzido por um robô industrial montado em plataforma móvel, o que permite levar o processo até peças grandes ou difíceis de transportar."}, {"q": "Qual a diferença para o PTA?", "a": "Os dois são soldagem de revestimento. O laser concentra a energia num ponto menor: menos diluição, menos distorção e zona afetada pelo calor mais estreita, ideal para peças de precisão."}], nome: 'Laser Cladding', titulo: 'Laser cladding robotizado com robô industrial móvel',
    resumo: 'Revestimento soldado a laser, com diluição mínima e precisão robótica, aplicado por robô industrial em plataforma móvel, inclusive na sua planta.',
    como: 'Um feixe laser de alta potência cria uma poça de fusão rasa sobre a peça, onde o pó metálico é injetado e fundido. O robô industrial de 6 eixos executa a trajetória programada com repetibilidade, formando cordões sobrepostos de espessura controlada e ligação metalúrgica com o metal base.',
    beneficios: ['Diluição mínima: a liga mantém suas propriedades', 'Zona termicamente afetada estreita, sem distorção', 'Ligação metalúrgica, sem destacamento', 'Precisão e repetibilidade robótica', 'Robô móvel: aplicação na planta do cliente', 'Menos sobremetal e menos usinagem posterior'],
    materiais: ['Stellite 6 (CoCrW)', 'Inconel 625', 'NiCrBSi e NiCrBSi + WC', 'Aços inox 420 e 316L'],
    aplicacoes: ['Eixos e hastes de precisão', 'Sedes e obturadores de válvulas', 'Rotores e componentes de turbinas', 'Moldes e matrizes', 'Peças grandes que não podem sair da planta'] },
  { slug: 'arco-submerso', faq: [{"q": "Quando usar arco submerso?", "a": "Quando é preciso reconstruir grandes volumes de material com alta produtividade, como em rolos de laminação, eixos e cilindros de grande porte."}], nome: 'Arco Submerso', titulo: 'Recuperação por soldagem a arco submerso',
    resumo: 'Altíssima taxa de deposição para reconstruir rolos, eixos e cilindros de grande porte.',
    como: 'Um arame contínuo é fundido por arco elétrico sob uma camada de fluxo granulado, que protege a poça de fusão. Com a peça girando, os cordões são sobrepostos de forma automatizada até recuperar a cota, seguidos de usinagem.',
    beneficios: ['Altíssima taxa de deposição', 'Solda limpa e sem respingos', 'Automatizado e repetível', 'Ideal para grandes volumes'],
    materiais: ['Aço carbono e baixa liga', 'Inox martensítico (420)', 'Inox 316L'],
    aplicacoes: ['Rolos de laminação e de lingotamento', 'Eixos de grande porte', 'Cilindros e tambores', 'Rodas e roletes'] },
  { slug: 'cromo-duro', faq: [{"q": "O cromo duro recupera peças desgastadas?", "a": "Sim. Após a deposição, a retífica devolve a cota original com acabamento polido ou espelhado."}, {"q": "Quando trocar cromo duro por HVOF?", "a": "Quando a vida útil do cromo é curta por abrasão severa. No case do pistão de prensa, a troca por carbeto via HVOF aumentou a vida útil da camada."}], nome: 'Cromo duro', titulo: 'Cromagem dura industrial',
    resumo: 'Cromo duro eletrolítico para recuperação dimensional, proteção contra desgaste e acabamento polido ou espelhado.',
    como: 'O cromo é depositado por eletrólise sobre a peça, formando uma camada dura e de baixo atrito. Após a deposição, a retífica e o polimento devolvem a cota e o acabamento de projeto.',
    beneficios: ['Baixo coeficiente de atrito', 'Acabamento polido ou espelhado', 'Recuperação dimensional', 'Resistência ao desgaste e à corrosão'],
    materiais: ['Cromo duro eletrolítico'],
    aplicacoes: ['Hastes de cilindros hidráulicos', 'Cilindros e rolos', 'Eixos e pistões', 'Moldes'] },
];

export const setores = [
  { slug: 'mineracao', nome: 'Mineração', texto: 'Cromo duro, aspersão térmica e soldagem aumentam a vida útil de equipamentos fora de estrada e de beneficiamento, reduzindo o custo operacional.', pecas: ['Mangas de eixo e pinos de sustentação', 'Caixas diferenciais e transmissões', 'Hastes de amortecedores', 'Rolos classificadores e peneiras', 'Transportadores de correia'], processos: ['hvof', 'pta', 'cromo-duro'] },
  { slug: 'oleo-e-gas', nome: 'Óleo & Gás e Petroquímica', texto: 'A confiabilidade exigida nessas unidades pede revestimentos de alta performance contra corrosão, abrasão e oxidação em altas temperaturas, aplicados por aspersão hipersônica e laser cladding. Unidade em Rio das Ostras, próxima à Bacia de Campos.', pecas: ['Luvas de desgaste', 'Carcaças de bombas e válvulas', 'Eixos de turbinas a gás e compressores', 'Tubos de caldeiras de força', 'Gavetas de válvulas de craqueamento'], processos: ['hvof', 'arc-spray'] },
  { slug: 'siderurgia', nome: 'Siderurgia', texto: 'Revestimentos para temperatura, abrasão e corrosão severas, além de reformas completas de equipamentos de laminação e pátio.', pecas: ['Cilindros de laminação (até 70 HRC)', 'Pinch rolls', 'Garras de sucata', 'Rodas de ponte rolante', 'Rolos de forno'], processos: ['hvof', 'pta', 'cromo-duro'] },
  { slug: 'naval', nome: 'Naval', texto: 'Parceira estratégica que atende aos elevados requisitos de qualidade, prontidão e prazo de entrega do setor naval.', pecas: ['Mancais e casquilhos', 'Eixos virabrequim', 'Coroas de pistão, cabeçotes e saias', 'Pás e poço de hélice', 'Estruturas metálicas (TSA)'], processos: ['arc-spray', 'hvof'] },
  { slug: 'papel-e-celulose', nome: 'Papel e Celulose', texto: 'Vida útil prolongada para peças expostas a ambientes químicos agressivos, umidade e abrasão.', pecas: ['Válvulas dosadoras e alimentadoras do digestor', 'Cilindros de peneiras de branqueamento', 'Pistões de prensa', 'Rolos secadores e puxadores', 'Rotores de tiragem de caldeira'], processos: ['hvof', 'cromo-duro'] },
  { slug: 'metal-mecanica', nome: 'Metal Mecânica', texto: 'Fabricantes de equipamentos (OEMs) têm na TFM uma parceira em tecnologia de superfícies desde o projeto.', pecas: ['Trocadores de calor e vasos de pressão', 'Bombas centrífugas e compressores', 'Válvulas', 'Máquinas operatrizes', 'Bobinas de trefila'], processos: ['hvof', 'arc-spray', 'cromo-duro'] },
  { slug: 'eolica', nome: 'Energia Eólica', texto: 'Recuperação de componentes de aerogeradores sem esperar meses por peças importadas: eixos, mancais e sedes recuperados com laser cladding, HVOF e usinagem de precisão, reduzindo o tempo de turbina parada.', pecas: ['Eixos principais e eixos de baixa rotação', 'Assentos de rolamento e mancais', 'Eixos e engrenagens de multiplicadoras', 'Pistões e hastes do sistema de pitch', 'Componentes do sistema de yaw'], processos: ['laser-cladding', 'hvof', 'arc-spray'] },
  { slug: 'textil', nome: 'Têxtil', texto: 'Cromo duro, oxi-cerâmicos e carbetos contra corrosão e desgaste abrasivo na produção de fios sintéticos.', pecas: ['Placas e buchas de aquecimento', 'Rolos defletores', 'Rotoconers', 'Rolos guia de bobinadeiras'], processos: ['cromo-duro', 'hvof'] },
];

export const glossario = [
  ['Aspersão térmica', 'Família de processos em que um material é fundido e projetado sobre a peça, formando uma camada aderida mecanicamente. Inclui HVOF, Arc Spray e Flame Spray.'],
  ['HVOF', 'High Velocity Oxy-Fuel: combustão de alta pressão acelera o pó a velocidades supersônicas, gerando camadas muito densas. Referência para carbonetos.'],
  ['Arc Spray', 'Dois arames fundidos por arco elétrico e atomizados por ar comprimido. Alta taxa de deposição para recuperação dimensional.'],
  ['Flame Spray', 'Pó ou arame fundido por chama oxiacetilênica. Versátil e econômico; com ligas autofluxantes pode ser refundido.'],
  ['Laser cladding', 'Soldagem de revestimento em que um feixe laser funde o pó sobre a peça, com diluição mínima e pouca entrada de calor.'],
  ['PTA', 'Plasma de arco transferido: soldagem de revestimento com pó metálico, camadas espessas e baixa diluição.'],
  ['Arco submerso', 'Soldagem com arame contínuo sob camada de fluxo, de altíssima deposição, usada para reconstruir grandes volumes.'],
  ['Cromo duro', 'Revestimento eletrolítico de cromo, de baixo atrito e alta dureza. Em muitas aplicações vem sendo substituído por HVOF.'],
  ['Diluição', 'Quanto do metal base se mistura à liga depositada na soldagem. Quanto menor, mais a camada mantém suas propriedades.'],
  ['ZTA', 'Zona termicamente afetada: região do metal base que teve a estrutura alterada pelo calor da soldagem.'],
  ['Sobremetal', 'Espessura depositada acima da cota final, removida depois na retífica ou usinagem para atingir a medida exata.'],
  ['Porosidade', 'Fração de vazios dentro de uma camada aspergida. Camadas HVOF ficam abaixo de 1%.'],
  ['Aderência', 'Resistência de ligação entre camada e metal base, medida em MPa em ensaio de tração.'],
  ['Dureza HRC / HV', 'Escalas de dureza Rockwell C e Vickers. Carbonetos de tungstênio passam de 1.100 HV.'],
  ['WC-Co', 'Carboneto de tungstênio com cobalto, liga de altíssima resistência à abrasão e erosão.'],
  ['Stellite', 'Família de ligas de cobalto-cromo-tungstênio resistentes a desgaste metal-metal, cavitação e calor.'],
  ['NiCrBSi (Colmonoy)', 'Liga autofluxante de níquel, refundida sobre a peça para formar uma camada densa contra desgaste e corrosão.'],
  ['Inconel 625', 'Superliga de níquel-cromo-molibdênio para corrosão severa e altas temperaturas.'],
  ['Jateamento abrasivo', 'Preparação da superfície que limpa e cria a rugosidade de ancoragem necessária para a aspersão.'],
  ['Metrologia dimensional', 'Medição precisa das cotas da peça antes e depois da recuperação, registrada em laudo.'],
];
