// Conteúdo das páginas de processo e setor (SEO). Apenas informações já presentes no site/material da TFM.
export const processos = [
  { slug: 'hvof', nome: 'HVOF', titulo: 'Revestimento HVOF (aspersão térmica hipersônica)',
    resumo: 'Camadas muito densas e aderentes de carbeto de tungstênio e ligas especiais, aplicadas em velocidade supersônica para resistir a abrasão, erosão e corrosão.',
    como: 'No HVOF (High Velocity Oxy-Fuel), a combustão em alta pressão acelera as partículas de pó a velocidades supersônicas. Elas atingem a peça com grande energia e formam um revestimento de baixa porosidade e alta aderência, com o substrato mantido em baixa temperatura.',
    beneficios: ['Alta dureza e resistência à abrasão', 'Baixa porosidade e alta aderência', 'Alternativa ao cromo duro em abrasão severa', 'Substrato em baixa temperatura, sem distorção'],
    materiais: ['Carbeto de tungstênio (WC-Co)', 'WC-CrC-Ni', 'Carbeto de cromo', 'Ligas de níquel'],
    aplicacoes: ['Pistões e hastes hidráulicas', 'Bobinas de trefila', 'Eixos de bombas e compressores', 'Roscas transportadoras', 'Válvulas e sedes'],
    caso: 'Pistão de prensa hidráulica (papel e celulose): substituição do cromo duro por carbeto de tungstênio aplicado por HVOF, aumentando a vida útil da camada.' },
  { slug: 'plasma', nome: 'Plasma', titulo: 'Aspersão térmica por plasma',
    resumo: 'Revestimentos cerâmicos e metálicos de alta pureza para proteção contra desgaste, corrosão e altas temperaturas.',
    como: 'Um arco elétrico ioniza o gás e forma um jato de plasma de altíssima temperatura, capaz de fundir materiais cerâmicos como óxido de cromo e óxido de alumínio, projetados sobre a peça com o substrato mantido frio.',
    beneficios: ['Aplica cerâmicas de alto ponto de fusão', 'Resistência ao desgaste e à corrosão química', 'Isolamento térmico e elétrico', 'Substrato em baixa temperatura'],
    materiais: ['Óxido de cromo (Cr₂O₃)', 'Óxido de alumínio', 'Ligas de níquel', 'Cerâmicas'],
    aplicacoes: ['Rolos e cilindros', 'Componentes têxteis (rolos guia, placas de aquecimento)', 'Selos e luvas de bombas', 'Peças expostas a altas temperaturas'] },
  { slug: 'arc-spray', nome: 'Arc Spray', titulo: 'Metalização por Arc Spray',
    resumo: 'Alta taxa de deposição para recuperação dimensional e proteção de grandes áreas contra corrosão.',
    como: 'Dois arames metálicos são fundidos por um arco elétrico e atomizados por ar comprimido, projetando gotas sobre a superfície preparada. É ideal para grandes áreas e recuperação de cotas com produtividade.',
    beneficios: ['Alta produtividade em grandes áreas', 'Recuperação dimensional econômica', 'Proteção anticorrosiva (zinco, alumínio)', 'Aplicável em campo'],
    materiais: ['Aço inox (ex.: INOX 420)', 'Aço carbono', 'Zinco e alumínio', 'Bronze e metal patente'],
    aplicacoes: ['Camisas e colos de eixos', 'Bobinas e polias', 'Estruturas navais e offshore', 'Mancais'],
    caso: 'Camisa recuperada no colo externo pelo processo Arc Spray com aço inox martensítico, seguida de usinagem de acabamento.' },
  { slug: 'pta', nome: 'PTA', titulo: 'Revestimento por PTA (plasma de arco transferido)',
    resumo: 'Camada soldada com ligação metalúrgica e baixa diluição, para impacto, abrasão e altas temperaturas.',
    como: 'No PTA, o arco de plasma é transferido para a peça e funde o pó metálico diretamente sobre a superfície, formando um cordão soldado de alta resistência e baixa diluição com o metal base.',
    beneficios: ['Ligação metalúrgica com a peça', 'Baixa diluição e controle preciso', 'Resistência a impacto e abrasão severa', 'Camadas espessas'],
    materiais: ['Ligas de cobalto (Stellite)', 'Ligas de níquel', 'Ligas de níquel com carbonetos'],
    aplicacoes: ['Sedes de válvulas', 'Componentes de mineração', 'Ferramentas e facas industriais', 'Peças sujeitas a impacto'] },
  { slug: 'cromo-duro', nome: 'Cromo duro', titulo: 'Cromagem dura industrial',
    resumo: 'Cromo duro eletrolítico para recuperação dimensional, proteção contra desgaste e acabamento polido ou espelhado.',
    como: 'O cromo é depositado por eletrólise sobre a peça, formando uma camada dura e de baixo atrito. Após a deposição, a retífica e o polimento devolvem a cota e o acabamento de projeto.',
    beneficios: ['Baixo coeficiente de atrito', 'Acabamento polido ou espelhado', 'Recuperação dimensional', 'Resistência ao desgaste e à corrosão'],
    materiais: ['Cromo duro eletrolítico'],
    aplicacoes: ['Hastes de cilindros hidráulicos', 'Cilindros e rolos', 'Eixos e pistões', 'Moldes'] },
];

export const setores = [
  { slug: 'mineracao', nome: 'Mineração', texto: 'Cromo duro, aspersão térmica e soldagem aumentam a vida útil de equipamentos fora de estrada e de beneficiamento, reduzindo o custo operacional.', pecas: ['Mangas de eixo e pinos de sustentação', 'Caixas diferenciais e transmissões', 'Hastes de amortecedores', 'Rolos classificadores e peneiras', 'Transportadores de correia'], processos: ['hvof', 'pta', 'cromo-duro'] },
  { slug: 'oleo-e-gas', nome: 'Óleo & Gás e Petroquímica', texto: 'A confiabilidade exigida nessas unidades pede revestimentos de alta performance contra corrosão, abrasão e oxidação em altas temperaturas, aplicados por aspersão hipersônica ou plasma. Unidade em Rio das Ostras, próxima à Bacia de Campos.', pecas: ['Luvas de desgaste', 'Carcaças de bombas e válvulas', 'Eixos de turbinas a gás e compressores', 'Tubos de caldeiras de força', 'Gavetas de válvulas de craqueamento'], processos: ['hvof', 'plasma', 'arc-spray'] },
  { slug: 'siderurgia', nome: 'Siderurgia', texto: 'Revestimentos para temperatura, abrasão e corrosão severas, além de reformas completas de equipamentos de laminação e pátio.', pecas: ['Cilindros de laminação (até 70 HRC)', 'Pinch rolls', 'Garras de sucata', 'Rodas de ponte rolante', 'Rolos de forno'], processos: ['hvof', 'pta', 'cromo-duro'] },
  { slug: 'naval', nome: 'Naval', texto: 'Parceira estratégica que atende aos elevados requisitos de qualidade, prontidão e prazo de entrega do setor naval.', pecas: ['Mancais e casquilhos', 'Eixos virabrequim', 'Coroas de pistão, cabeçotes e saias', 'Pás e poço de hélice', 'Estruturas metálicas (TSA)'], processos: ['arc-spray', 'hvof'] },
  { slug: 'papel-e-celulose', nome: 'Papel e Celulose', texto: 'Vida útil prolongada para peças expostas a ambientes químicos agressivos, umidade e abrasão.', pecas: ['Válvulas dosadoras e alimentadoras do digestor', 'Cilindros de peneiras de branqueamento', 'Pistões de prensa', 'Rolos secadores e puxadores', 'Rotores de tiragem de caldeira'], processos: ['hvof', 'plasma', 'cromo-duro'] },
  { slug: 'metal-mecanica', nome: 'Metal Mecânica', texto: 'Fabricantes de equipamentos (OEMs) têm na TFM uma parceira em tecnologia de superfícies desde o projeto.', pecas: ['Trocadores de calor e vasos de pressão', 'Bombas centrífugas e compressores', 'Válvulas', 'Máquinas operatrizes', 'Bobinas de trefila'], processos: ['hvof', 'arc-spray', 'cromo-duro'] },
  { slug: 'textil', nome: 'Têxtil', texto: 'Cromo duro, oxi-cerâmicos e carbetos contra corrosão e desgaste abrasivo na produção de fios sintéticos.', pecas: ['Placas e buchas de aquecimento', 'Rolos defletores', 'Rotoconers', 'Rolos guia de bobinadeiras'], processos: ['plasma', 'cromo-duro', 'hvof'] },
];
